#!/bin/csh

setenv LD_LIBRARY_PATH ../lib:{$LD_LIBRARY_PATH}
setenv CLASSPATH ./classes:../lib/classes:$JAVA_HOME/lib/classes.zip
#unsetenv JAVA_COMPILER

java Test

if ( $status == "0" ) then
        echo All tests succeeded!
endif
